### ISSUE TITLE
Требования: "Проблема"

### ISSUE THREAD

**Issue by vkamiansky** [hypnospinner/Project-Focus#27]
Составить описание работы и требования к реализации фичи "Проблема" из [списка фич первого релиза](https://github.com/hypnospinner/Project-Focus/wiki). 

Разбить на задачи в слоях View, ViewModel, Business. 

Проставить свои оценки трудоёмкости для каждой задачи в идеальных днях.

В данной задаче требуется активность всего коллектива. Вопросы и комментарии приветствуются.)

**Comment by vkamiansky** [comment]
Current task decomposition for this story:

[ ] Model - Add business entitiy(ies) for Problem; Approach this through domain events model (see TDD);
[ ] Service - Add business logic for problem-related events;
[ ] View Model - Add presentation logic for problem creation, editing and resolution;
[ ] View - Add pages for problem list and problem specification; Add mock view-models;
[ ] Data - Add simple 'event-queue' substitute and JSON local storage for problem-related data;
[ ] UI - Add styles for all problem-related pages.
[ ] Test - Add unit tests for view models and services;

Estimates required. Comments appreciated)

**Comment by hypnospinner** [comment]
Немного посидев в коде (и не понимая процентов 80% написанного) появились вопросы.
1. Я понимаю как организованы проекты, но не очень понимаю почему это работает. Это действительно хорошо и удобно, что ViewModel в одном проекте, а Model, View в других. Но каким образом проект "клеится"?
2. Получается в `ProjectFocus.ViewModel` в `MainViewModel` должен быть метод создания "настоящей" проблемы, а не Autofac's имитатор. Тогда получается, что мы переходим на Page Problem, там заполняем поля, которые уже инициализируют настоящий Problem, который потом по нажатию некой кнопки должен отправится на сервер и сохранится на устройстве. Ошибаюсь ли я?
3. Появилась возможно неплохая идея сделать своего рода иллюстративный Naviagtion Map, который покажет с какой страницы и как можно попасть на какую и где какие ViewModel нужны.
4. Когда мы уходим со Page, данные о том, что на ней как-то сохраняются? То есть открыв например страницу со списком дел мы генерим ее по-новой (подгружаем задачи) или она как-то сохраняется и обновляется при открытии?

**Comment by vkamiansky** [comment]
1. **Autofac** нами используется не для имитации, а как раз для склеивания проекта. 

В ООП Dependency Injection используется для композиции приложений. Вся склейка происходит в проекте **ProjectFocus.Integration** в классе `CompositionRoot`. Мы сначала рассказываем Autofac'у как сопоставлять те типы-обобщения, которые нам потребуются при композиции с их типами реализациями, а потом просим создать реализацию для обобщения IMainViewModel по этим правилам.

   Вот расшифровка того, как мы объясняем Autofac'у как заполнять поля абстрактных типов объектами реализующих их классов.

```c#
var viewAssembly = typeof(MainPage).Assembly;

builder.RegisterAssemblyTypes(viewAssembly)
            .Where(t => t.Name.EndsWith("Page", StringComparison.InvariantCultureIgnoreCase))
            .Keyed<ContentPage>(t => t.Name);
```

Когда встретится поле типа `IIndex<string, ContentPage>`, его нужно заполнить индексом объектов всех классов из сборки, где есть `MainPage`, имена которых заканчиваются на 'Page' без учёта регистра, а в качестве ключа индекса использовать имя объекта, так чтобы из этого индекса по ключу `["MainPage"]` мы получали настоящий объект класса MainPage.

```c#
var viewModelAssembly = typeof(MainViewModel).Assembly;

builder.RegisterAssemblyTypes(viewModelAssembly)
            .Where(t => t.Name.EndsWith("ViewModel", StringComparison.InvariantCultureIgnoreCase))
            .AsImplementedInterfaces()
            .PropertiesAutowired();
```
Когда встретится поле типа интерфейса, реализуемого классом из сборки, в которой есть `MainViewModel`, его нужно заполнить объектом реализующего класса + делать это не только для параметров конструктора, но и для свойств, где встречается тип-абстракция. Участвуют только те классы из сборки, имена которых оканчиваются на "ViewModel". Например, встретилось `IMainViewModel` заполнить его объектом `MainViewModel`, встретилось `Func<IProblemViewModel>` - заполнить функцией, которая возвращает объект типа `ProblemViewModel`.

```c#
var serviceAssembly = typeof(NavigationService).Assembly;

builder.RegisterAssemblyTypes(serviceAssembly)
            .Where(t => t.Name.EndsWith("Service", StringComparison.InvariantCultureIgnoreCase))
            .AsImplementedInterfaces()
            .PropertiesAutowired()
            .SingleInstance();
```
То же для сервисов, но здесь каждого сервиса будет создан всего один экземпляр на всё приложение.

```c#
builder.RegisterInstance(navigation)
            .As<NavigationPage>();
```
Когда встретится поле типа `NavigationPage`, просто заполнить его данным конкретным объектом.

И финальная стадия склейки: собрать главную View Model, а в ней по выше описанным правилам подставятся и сервисы и другие View Model - объекты.

```c#
return container.Resolve<IMainViewModel>();
```

2.  **Autofac** возвращает настоящую реализацию `IProblemViewModel`, построенную по правилам из `CompositionRoot` в **ProjectFocus.Integration**. Имитацию возвращает **Moq** в методе тестирования `NavigationTest` класса `MainViewModelTests` в проекте **ProjectFocus.ViewModel.Test**.  Сама `MainViewModel` знает, что делать с View Model проблемы (навигировать на неё по нажатию кнопки), но реальная или имитационная эта View Model будет его не касается.

3. Идея хорошая. Ещё раз напомню, что выбранная схема навигации - [иерархическая](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/hierarchical). Это по сути стек. Можно применить идеи стека при отображении карты навигации.

4. Данные не на странице, а в связанной с ней View Model. Сейчас, когда мы нажимаем кнопку назад, мы просто убираем из стека страницы и попадаем на предыдущие, на которых всё сохраняется, но когда мы навигируем куда-то вперёд, конечно же создастся новая страница и новая же для неё View Model.

@hypnospinner: плиз, комментируй, насколько ситуация прояснилась, остались ли ещё трудности?

**Comment by vkamiansky** [comment]
@hypnospinner  Хорошие замечания. В проекте **ProjectFocus.Model** будут храниться бизнес-модели, такие как Problem. Они будут возвращаться во вью модели сервисами из **ProjectFocus.Service** и принимают сервисы тоже их. Ссылка из **ProjectFocus.ViewModel** и **ProjectFocus.Interface** на **ProjectFocus.Model** обязательна. Если их нет, надо добавить. **ProjectFocus.ViewModel** не должен ссылаться на **ProjectFocus.Service**, проект содержащий реализацию бизнес-логики. Всю бизнес-логику мы получаем по интерфейсу.

**Comment by vkamiansky** [comment]
> 1. Как я понял:
>    Когда мы пишем
> 
> ```cs
> var viewAssembly = typeof(MainPage).Assembly;
> ```
> 
> нам "возвращается" проект в котором определен этот тип и далее мы работаем внутри него.

Немного не так. Следует понимать, что все эти действия происходят во время исполнения программы. Проект компилируется в сборку и у каждого типа можно узнать в какой сборке он находится. Это мы здесь и делаем. Потом мы говорим автофаку, что в этой сборке нужно найти все классы и описываем как эти классы регистрировать, чтобы когда мы используем простое объявление обобщения, как в показанном тобой примере, автофак знал что вместо обобщения подставлять.

Следует отметить, что в нашем коде композиции мы разбираем классы нескольких сборок.

Сделать вью-модель для проблемы - отличная идея. Поддерживаю! Можешь заодно создать issue для этого. "клиентская часть фичи "проблема": итерация 0"

**Comment by hypnospinner** [comment]
> <...>В проекте **ProjectFocus.Model** будут храниться бизнес-модели, такие как Problem. Они будут возвращаться во вью модели сервисами из **ProjectFocus.Service** и принимают сервисы тоже их. <...> **ProjectFocus.ViewModel** не должен ссылаться на **ProjectFocus.Service**, проект содержащий реализацию бизнес-логики. Всю бизнес-логику мы получаем по интерфейсу.

@vkamiansky не понял. Если **ProjectFocus.Sevice** отправляет Model'и к ViewModel'ям то как **ProjectFocus.ViewModel** и **ProjectFocus.Service** могут быть не связаны?

> For some reasons I can't reference ProjectFocus.Model assembly in ProjectFocus.ViewModel

В `ProblemViewModel.cs` он просто не принимает строчку `using ProjectFocus.Model`, выдавая это за ошибку. А на модель мне там надо ссылаться, чтобы делать дата-байндинги

**Comment by vkamiansky** [comment]
> @vkamiansky не понял. Если **ProjectFocus.Sevice** отправляет Model'и к ViewModel'ям то как **ProjectFocus.ViewModel** и **ProjectFocus.Service** могут быть не связаны?

Очень просто. В проекте **ProjectFocus.Interface** будет, например, интерфейс `IProblemService`, который содержит метод `Problem GetProblem(int id)`. Класс Problem будет находиться в проекте **ProjectFocus.Model**, а в ProblemViewModel, который в проекте **ProjectFocus.ViewModel** будет фигурировать `IProblemService` и никакого `ProblemService` из **ProjectFocus.Service**.  Вместо `IProblemService` экземпляр `ProblemService` подставит Autofac. И отсюда получается, что **ProjectFocus.ViewModel** должен видеть **ProjectFocus.Model** и **ProjectFocus.Interface**; **ProjectFocus.Interface** должен видеть **ProjectFocus.Model**, а **ProjectFocus.Service** должен видеть **ProjectFocus.Model** и **ProjectFocus.Interface**. **ProjectFocus.ViewModel** не должен видеть **ProjectFocus.Service**. Всех видит только **ProjectFocus.Integration**, где живёт Autofac - ещё бы, ему ведь всех их дружить!

**Comment by vkamiansky** [comment]
> В `ProblemViewModel.cs` он просто не принимает строчку `using ProjectFocus.Model`, выдавая это за ошибку. А на модель мне там надо ссылаться, чтобы делать дата-байндинги

Ну да, потому, что я ещё не добавил ссылку из ProjectFocus.ViewModel на ProjectFocus.Model. Это как раз самое время исправить.)
![image](https://user-images.githubusercontent.com/6636792/50047704-eb722c00-00cb-11e9-9ce4-1997d1502014.png)
![image](https://user-images.githubusercontent.com/6636792/50047710-0775cd80-00cc-11e9-9a6d-43facf58df0b.png)

**Comment by vkamiansky** [comment]
Реализация фичи "Проблема" разделяется по слоям. Каждый новый слой добавляет детализацию при реализации фичи и может добавлять пересечение с другими фичами при сохранении независимости.
