### ISSUE TITLE
Провести встречу + обсудить задел по проекту + настроить окружение разработки

### ISSUE THREAD

**Issue by vkamiansky** [hypnospinner/Project-Focus#30]
Было бы здорово провести встречу по проекту до начала milestone 2 и сделать следующее:

- Обсудить текущий задел по проекту (архитектуру, проектирование);
- Настроить у каждого участника окружение для разработки;
- Составить требования по фиче "Проблема".

Пожалуйста, коллеги @hypnospinner @SabinaAlieva @wndrvie, пишите свои предложения ;) Я свободен в будние дни после 7 вечера, в субботу 8 дек. днём,  на неделе, начиная с 10 дек.  пока точно не знаю.

**Comment by hypnospinner** [comment]
В ближайшее время девчонки встретится не могут. У меня есть время и возможность, на выходных в субботу или воскресенье (я свободен в принципе в любое время, но в субботу лучше к утру-дню)

**Comment by hypnospinner** [comment]
Ещё мне стало интересно ФП и F# (мы будем его использовать в back-end'е как я понял). Вы не можете дать несколько простеньких задач для практики?

**Comment by vkamiansky** [comment]
Приветствую! Суббота утро мне отлично подходит. Как насчёт 10:00 Финляндский вокзал?

**Comment by hypnospinner** [comment]
Мне тоже удобно

**Comment by vkamiansky** [comment]
По F# есть [моя давняя маленькая статья](https://github.com/vkamiansky/omniture-interceptor/blob/master/fsharp-in-short.md), есть [большой сайт от Microsoft](https://docs.microsoft.com/en-us/dotnet/fsharp/). В качестве задачек предлагается [Рауль Рохас "Вводный материал по лямбда-исчислению"(анг.)](http://www.inf.fu-berlin.de/lehre/WS01/ALPI/lambda.pdf)
