### ISSUE TITLE
Реализация проблемы на клиенте

### ISSUE THREAD

**Issue by hypnospinner** [hypnospinner/Project-Focus#34]
### Реализовать форму заполнения проблемы на клиента (+ сохранение?)

Нужно:

- [ ] создать Model для проблемы
- [ ] создать ViewModel для проблемы
- [ ] создать View для проблемы (поля для ввода простых данных)

**Comment by vkamiansky** [comment]
Также предлагается создать заглушки под сохранение данных проблем. Простейшая серверная функциональность для сохранения проблем в Mongo DB становится доступна в #35. Но в данном случае, будет нелишним ознакомиться с вариантами хранения данных на устройстве. Возможность хранить данные только на устройстве может оказаться не менее важной, чем возможность сохранить данные на сервере. Возможно, стоит создать для этого отдельную issue.

**Comment by vkamiansky** [comment]
По поводу сохранения на устройстве - Json представляется наиболее подходящим вариантом. Моё правило: никаких авторских алгоритмов)) По поводу синхронизации - серьёзное архитектурное решение, его лучше обсудить всем вместе. Я бы сделал на главном экране снизу переключатель онлайн-оффлайн. Это уже при первом рассмотрении выглядит, как серьёзная отдельная фича вне скоупа первой версии. Всё требует устного обсуждения имхо.

**Comment by hypnospinner** [comment]
@vkamiansky 
О кнопке офлайн/онлайн - не уверен, что это хорошая идея. Будет только отвлекать пользователя лишней функциональностью (имхо). Мне кажется было бы неплохо делать это «за спиной» пользователя, но тогда нужно обговорить правила разрешения таких несоответствий (сделано где-то = сделано везде?)

**Comment by hypnospinner** [comment]
Разбираю, что происходит в программе.
Все начинается с **ProjectFocus.App.xaml.cs** где мы от _Autofac_ получаем **MainViewModel**, создаем **NavigationPage** (объект управляющий переходом между page). Дальше у нас выполняется код в **MainViewModel**, когда мы нажимаем на кнопку (там биндинг на **ProblemCommand**). И вот тут вопрос. Почему то, что объявлено как property работает как метод?
```c#
// This is an automatic view-model-producing factory method
// brought to us by Autofac.
public Func<IProblemViewModel> GetProblemViewModel { get; set; }

// some code

NavigationService.Navigate(PageKey.Problem, GetProblemViewModel()));
```

Я потом посмотрел на определения (alt+f12 стало очень часто нажиматься) и понял, что это делегат, т.е. он как бы и должен быть методом, который будет возвращать инициализированный объект generic-типа (если так можно сказать). 

Когда мы нажимаем на кнопку, autofac генерит ProblemViewModel и мы преходим на его страницу. И вот тут наступает момент истины. Где вот во всей этой кутерьме должен появляться model проблемы? Autofac по идее за него не должен отвечать, я не видел, чтобы autofac регал что-то с model. Значит модель должна создаваться где-то во ViewModel, но как тогда мне обеспечить ее создание. Я думаю, что правильно создать Model в момент нажатия на кнопку добавить проблему на страницу инициализации полей (мы проверяем инициализированы ли обязательные поля и если да - создаем проблемы и как-то ее созраняем) тогда можно поля очистить и предложить юзеру создать еще проблему.

![problem](https://user-images.githubusercontent.com/40162026/50426012-b8325880-0894-11e9-956e-7d5b51934216.jpg)
_Более визуальное видение происходящего_

Если я все правильно понял, то кажется я сделал качественный шаг вперед в понимании того, как все происходит

**Comment by vkamiansky** [comment]
@hypnospinner Да, это шаг вперёд. Отличная картинка! В ProblemViewModel у нас будет свойство `IProblemService problemService {get;set;}`, тоже автоматически заполняемое Autofac'ом (тут всё настроено и зарегистрировано). У сервиса будет метод `AddNewProblem(Problem problem)`. Как нетрудно догадаться, Problem - это бизнес-объект из проекта **ProjectFocus.Model**, который по нажатию кнопки "Create", и значит по срабатыванию `ICommand CreateCommand` во вью модели должен быть просто создан на основании заполненных свойств вью модели. `Problem` создаётся вручную через `new Problem{...}`. Вообще, сервисы принимают и возвращают либо простые типы либо модели из **ProjectFocus.Model**. В свою очередь методы сервисов используют репозитории, а репозитории получают и возвращают объекты данных из **ProjectFocus.DataModel**. Но это детали, а картинка всё отражает абсолютно верно. `Func<T>` можно называть а-ля ООП фабричным методом, можно функцией, можно делегатом, как понятнее. Мне почему-то слово "делегат" не нравится, оно будит во мне воспоминания о страшных гонениях на ФП в C# 1.0 :))

**Comment by vkamiansky** [comment]
Картинки и информацию нужно будет перенести в вики. А дальнейшее создание issue будет проходить послойно.
