### ISSUE TITLE
Встреча. Обсуждение страниц приложения

### ISSUE THREAD

**Issue by hypnospinner** [hypnospinner/Project-Focus#38]
## Структура страниц приложения

Задача: понять каким образом мы будем связывать те или иные страницы, чтобы понимать, как организовать программную часть, понять что конкретно нам нужно.

Предлагайте время и место.
Лично я свободен в любой день кроме 30.12 и 03.01 (ну 31 пожалуй брать не стоит - Новый Год все таки)

**Comment by vkamiansky** [comment]
Думаю, что после Нового года. Как вам, числа 3-го? Когда все уже придут в себя после праздника.:)

**Comment by hypnospinner** [comment]
@vkamiansky
Если можно то давайте 4-го? Я 3-го буду в Финляндии просто.

**Comment by vkamiansky** [comment]
4-е мне вполне подходит. Но где же активность наших замечательных участниц проекта в комментах? :)

**Comment by wndrvie** [comment]
А мы тут 😃
Меня 4 тоже устраивает.

**Comment by hypnospinner** [comment]
### Повестка
1. Структура страниц приложения
   Исходя из [возможностей первого релиза](https://github.com/hypnospinner/Project-Focus/wiki#Возможности-первого-релиза) нужно составить "карту" экранов приложений, а так же проработать каждый экран и понять, что на нем должно быть

1. Разобрать новый способ навигации (см. #41)

Предлагайте темы для обсуждения.

@vkamiansky @wndrvie @SabinaAlieva Когда и где встречаемся? Думаю можно как в прошлый раз, если всем это будет удобно. По времени - предлагайте, я свободен весь день.

**Comment by vkamiansky** [comment]
@hypnospinner @wndrvie @SabinaAlieva Привет привет! Всех с наступившим!))) Предлагаю, как в прошлый раз встретиться в районе 11 у Финляндского вокзала.

С повесткой согласен. Также можно добавить в неё немного обсуждения серверной функциональности, и **процесса** разработки и интеграции нашего проекта.

**Comment by vkamiansky** [comment]
https://wbd.ms/share/v2/aHR0cHM6Ly93aGl0ZWJvYXJkLm1pY3Jvc29mdC5jb20vYXBpL3YyLjAvd2hpdGVib2FyZHMvcmVkZWVtLzY4Yjc3NDFjNjVmMjQxYzNhNjRlMGY1NGJkZTVkYTcxX0JCQTcxNzYyLTEyRTAtNDJFMS1CMzI0LTVCMTMxRjQyNEUzRA==

**Comment by vkamiansky** [comment]
- Обсудили теорию (связи между слоями, обратные категории)
- Обсудили новый механизм навигации
